Algoritmo "parOUimpar"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/05/2024
Var
// Seção de Declarações das variáveis 
N:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("digite qualquer numero ")
   leia(N)
   se (N % 2=0) entao
      escreval("o numero ", N ," é par")
   senao
        escreval("o numero ", N ,"é impar")
   fimse

Fimalgoritmo